### PR TITLE
made exceptions more detailed

### PR DESCRIPTION
**Pull request by gaukes**
@dhadfieldmenell @ronuchit

### CODE REVIEW

**Comment by ronuchit** [comment]
The indentation in the new test file, test_errors_exceptions, isn't consistent with that in the other files.

**Comment by ronuchit** [comment]
It's also not consistent in src/errors_exceptions.py.

**Comment by gaukes** [comment]
Forgot to set sublime to soft tabs. Indentation should be fixed now.

**Comment by ronuchit** [comment]
Great, thanks, and I'm sure you already have this in mind but don't forget to wrap exception-handling around the entire code at some high-level point. Now that I think about it, you'll want to find a creative way to do this "well" (in the sense that, you shouldn't just say "try: except (_every single exception you defined_)" because then if someone defines a new Exception in errors_exceptions.py, they'll have to change this as well). Best way I can think of is to have a try/except that exits gracefully upon catching any Exception belonging to errors_exceptions.py. Or even better, have those exceptions you defined have a flag that indicates they should be handled gracefully in main.py.

**Comment by gaukes** [comment]
Oh ya, I forgot to write that part down in my notes. I decided to make a new generic exception that everything in errors_exceptions.py will subclass. Seems like a natural way to do it.

**Pull request merged**
